sudo: required
services:
    - docker
before_install:
    - docker build -t romil618/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run romil618/react-test npm test -- --coverage

after_success:
    - docker build -t romil618/multi-client  ./client
    - docker build -t romil618/multi-server ./server
    - docker build -t romil618/multi-nginx ./nginx
    - docker build -t romil618/multi-worker ./worker
## log in to the docker CLI#
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

## Take these images and push them to docker hub
    - docker push romil618/multi-client
    - docker push romil618/multi-nginx
    - docker push romil618/multi-server
    - docker push romil618/multi-worker

deploy:
    edge: true
    environemnt:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-561501655179
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY

